//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



//INSTANT C# NOTE: Formerly VB project-level imports:
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Xml.Linq;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.HtmlControls;

namespace WESNet.DNN.Modules.ContentDejour
{

  public partial class CategoryEditor
  {

	///<summary>
	///gvList control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.GridView gvList;

	///<summary>
	///btnAdd control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::System.Web.UI.WebControls.LinkButton btnAdd;
  }
}
